import { Bell, Box, Building2, CheckCircle2, ChevronDown, ClipboardList, FileText, LayoutDashboard, PackageCheck, Plus, Search, Settings, ShoppingCart, Store, Users, type LucideIcon } from 'lucide-react';

type NavItem = { label: string; icon: LucideIcon; active?: boolean; badge?: string };
type RequestSummary = { id: string; item: string; meta: string; status: 'pending' | 'approved' | 'ordered' | 'draft' };
type Stat = { label: string; value: string; icon: LucideIcon; trend: string };

const nav: NavItem[] = [{label:'Overview',icon:LayoutDashboard,active:true},{label:'Requests',icon:ClipboardList,badge:'6'},{label:'Purchase orders',icon:ShoppingCart},{label:'Receiving',icon:PackageCheck},{label:'Catalog',icon:Box},{label:'Suppliers',icon:Store},{label:'Team',icon:Users},{label:'Settings',icon:Settings}];
const requests: RequestSummary[]=[{id:'MR-1048',item:'Milwaukee M18 Fuel Drill Kit',meta:'J. Martinez · Riverside Commons',status:'pending'},{id:'MR-1047',item:'3/4 in. Plywood — 24 sheets',meta:'A. Chen · Oak Street Residences',status:'approved'},{id:'MR-1046',item:'Simpson Strong-Tie joist hangers',meta:'D. Brooks · Harbor Point',status:'ordered'},{id:'MR-1045',item:'Concrete anchors & fasteners',meta:'S. Patel · Riverside Commons',status:'draft'}];
const stats: Stat[]=[{label:'Awaiting approval',value:'6',icon:ClipboardList,trend:'2 due today'},{label:'Open purchase orders',value:'12',icon:ShoppingCart,trend:'$48,320 committed'},{label:'Deliveries this week',value:'8',icon:PackageCheck,trend:'3 arriving today'},{label:'Month to date',value:'$72.4k',icon:FileText,trend:'8% under budget'}];

export default function Dashboard(){return <div className="shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><Building2 size={17}/></span><span>Supplyr</span></div><div className="workspace">Workspace</div><nav className="nav">{nav.map(({label,icon:Icon,active,badge})=><a key={label} href="#" className={active?'active':''}><Icon size={18}/><span>{label}</span>{badge&&<b className="badge">{badge}</b>}</a>)}</nav><div className="user"><span className="avatar">AM</span><div><div style={{fontSize:13,fontWeight:600}}>Alex Morgan</div><small>Purchasing admin</small></div></div></aside><main className="main"><header className="topbar"><div className="top-title">Northstar Construction <ChevronDown size={14} style={{verticalAlign:'middle'}}/></div><div className="actions"><button className="icon-btn" aria-label="Search"><Search size={18}/></button><button className="icon-btn" aria-label="Notifications"><Bell size={18}/></button><button className="btn primary"><Plus size={17}/> New request</button></div></header><div className="content"><section className="welcome"><div><h1>Good morning, Alex</h1><p>Here’s what needs your attention today.</p></div></section><section className="stats">{stats.map(({label,value,icon:Icon,trend})=><article className="stat" key={label}><div className="stat-head"><span>{label}</span><span className="stat-icon"><Icon size={17}/></span></div><strong>{value}</strong><div className="trend">{trend}</div></article>)}</section><section className="grid"><div><article className="card"><div className="card-head"><h2>Recent material requests</h2><a href="#">View all →</a></div>{requests.map(({id,item,meta,status})=><div className="request" key={id}><span className="request-icon"><Box size={19}/></span><div><strong>{item}</strong><div className="meta"><span>{id}</span><span>•</span><span>{meta}</span></div></div><span className={`status ${status}`}>{status}</span></div>)}</article></div><div><article className="card"><div className="card-head"><h2>Recent activity</h2><a href="#">View all</a></div><div className="activity"><span className="dot"/><div><p><b>PO-2026-0084</b> was partially received by Maya</p><time>18 minutes ago</time></div></div><div className="activity"><span className="dot" style={{background:'#469077'}}/><div><p><b>MR-1047</b> was approved by Luis</p><time>1 hour ago</time></div></div><div className="activity"><span className="dot" style={{background:'#7185b0'}}/><div><p><b>PO-2026-0082</b> was sent to White Cap</p><time>Yesterday at 4:32 PM</time></div></div></article><section className="quick"><CheckCircle2 size={22}/><h3>Connected workflow</h3><p>Received materials flow into Stockr and project costs sync to Buildr automatically.</p><button className="btn">Manage integrations</button></section></div></section></div></main></div>}
