-- Supplyr shares the Stockr Supabase project on the free tier.
-- Isolation rule: this migration creates/uses ONLY supplyr_* application objects (plus auth.users references).
-- It must never alter or delete stockr_* tables.
-- Supplyr core schema. Tenant membership is resolved from auth.uid() in every policy.
create extension if not exists pgcrypto;
create type public.supplyr_member_role as enum ('employee','supervisor','purchasing','admin');
create type public.supplyr_request_status as enum ('draft','submitted','approved','rejected','ordered','partially_received','received','cancelled');
create type public.supplyr_po_status as enum ('draft','review','sent','acknowledged','partially_received','received','cancelled');

create table public.supplyr_companies (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, po_prefix text not null default 'PO', next_po_number bigint not null default 1, created_at timestamptz not null default now());
create table public.supplyr_company_members (company_id uuid not null references public.supplyr_companies on delete cascade, user_id uuid not null references auth.users on delete cascade, role public.supplyr_member_role not null default 'employee', supervisor_id uuid references auth.users, active boolean not null default true, primary key(company_id,user_id));
create table public.supplyr_projects (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.supplyr_companies on delete cascade, name text not null, code text, buildr_project_id text, active boolean not null default true, unique(company_id,id));
create table public.supplyr_suppliers (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.supplyr_companies on delete cascade, name text not null, email text, phone text, address jsonb not null default '{}', active boolean not null default true, unique(company_id,id));
create table public.supplyr_catalog_items (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.supplyr_companies on delete cascade, name text not null, description text, internal_sku text, unit text not null default 'each', category text, manufacturer text, brand text, active boolean not null default true, created_at timestamptz not null default now(), unique(company_id,id), unique(company_id,internal_sku));
create table public.supplyr_supplier_items (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.supplyr_companies on delete cascade, catalog_item_id uuid not null, supplier_id uuid not null, supplier_sku text, unit_price numeric(14,4), currency text not null default 'USD', is_preferred boolean not null default false, unique(company_id,catalog_item_id,supplier_id), foreign key(company_id,catalog_item_id) references public.supplyr_catalog_items(company_id,id) on delete cascade, foreign key(company_id,supplier_id) references public.supplyr_suppliers(company_id,id) on delete cascade);
create table public.supplyr_purchasing_rules (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.supplyr_companies on delete cascade, catalog_item_id uuid, category text, rule_type text not null check(rule_type in ('preferred_supplier','required_supplier','preferred_brand','required_brand')), supplier_id uuid, value text, priority integer not null default 100, active boolean not null default true, foreign key(company_id,catalog_item_id) references public.supplyr_catalog_items(company_id,id), foreign key(company_id,supplier_id) references public.supplyr_suppliers(company_id,id));
create table public.supplyr_material_requests (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.supplyr_companies on delete cascade, request_number bigint not null, requested_by uuid not null references auth.users, project_id uuid, supervisor_id uuid references auth.users, status public.supplyr_request_status not null default 'draft', requested_for date, notes text, submitted_at timestamptz, decided_at timestamptz, decided_by uuid references auth.users, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(company_id,request_number), unique(company_id,id), foreign key(company_id,project_id) references public.supplyr_projects(company_id,id));
create table public.supplyr_request_items (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.supplyr_companies on delete cascade, request_id uuid not null, catalog_item_id uuid, description text not null, quantity numeric(14,3) not null check(quantity>0), unit text not null, notes text, approved_quantity numeric(14,3), selected_supplier_id uuid, selected_brand text, substitution_allowed boolean not null default false, unique(company_id,id), foreign key(company_id,request_id) references public.supplyr_material_requests(company_id,id) on delete cascade, foreign key(company_id,catalog_item_id) references public.supplyr_catalog_items(company_id,id), foreign key(company_id,selected_supplier_id) references public.supplyr_suppliers(company_id,id));
create table public.supplyr_purchase_orders (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.supplyr_companies on delete cascade, po_number text not null, supplier_id uuid not null, project_id uuid, status public.supplyr_po_status not null default 'draft', ordered_at timestamptz, expected_at date, subtotal numeric(14,2) not null default 0, tax numeric(14,2) not null default 0, shipping numeric(14,2) not null default 0, notes text, created_by uuid not null references auth.users, created_at timestamptz not null default now(), unique(company_id,po_number), unique(company_id,id), foreign key(company_id,supplier_id) references public.supplyr_suppliers(company_id,id), foreign key(company_id,project_id) references public.supplyr_projects(company_id,id));
create table public.supplyr_purchase_order_items (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.supplyr_companies on delete cascade, purchase_order_id uuid not null, request_item_id uuid, description text not null, supplier_sku text, quantity numeric(14,3) not null check(quantity>0), received_quantity numeric(14,3) not null default 0 check(received_quantity>=0), unit text not null, unit_price numeric(14,4) not null default 0, backordered_quantity numeric(14,3) not null default 0, substitution_for uuid, unique(company_id,id), foreign key(company_id,purchase_order_id) references public.supplyr_purchase_orders(company_id,id) on delete cascade, foreign key(company_id,request_item_id) references public.supplyr_request_items(company_id,id));
create table public.supplyr_receipts (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.supplyr_companies on delete cascade, purchase_order_id uuid not null, received_by uuid not null references auth.users, received_at timestamptz not null default now(), packing_slip text, notes text, unique(company_id,id), foreign key(company_id,purchase_order_id) references public.supplyr_purchase_orders(company_id,id));
create table public.supplyr_receipt_items (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.supplyr_companies on delete cascade, receipt_id uuid not null, purchase_order_item_id uuid not null, quantity numeric(14,3) not null check(quantity>0), condition text default 'accepted', stockr_sync_status text default 'pending', foreign key(company_id,receipt_id) references public.supplyr_receipts(company_id,id) on delete cascade, foreign key(company_id,purchase_order_item_id) references public.supplyr_purchase_order_items(company_id,id));
create table public.supplyr_integrations (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.supplyr_companies on delete cascade, kind text not null check(kind in ('stockr','buildr','currentflow_sso')), enabled boolean not null default false, configuration jsonb not null default '{}', unique(company_id,kind));
create table public.supplyr_audit_log (id bigint generated always as identity primary key, company_id uuid not null references public.supplyr_companies on delete cascade, actor_id uuid references auth.users, entity_type text not null, entity_id uuid not null, action text not null, before_data jsonb, after_data jsonb, created_at timestamptz not null default now());

create or replace function public.supplyr_is_company_member(cid uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.supplyr_company_members m where m.company_id=cid and m.user_id=auth.uid() and m.active) $$;
create or replace function public.supplyr_has_company_role(cid uuid, roles public.supplyr_member_role[]) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.supplyr_company_members m where m.company_id=cid and m.user_id=auth.uid() and m.active and m.role=any(roles)) $$;

alter table public.supplyr_companies enable row level security;
create policy company_read on public.supplyr_companies for select using(public.supplyr_is_company_member(id));
create policy company_admin_update on public.supplyr_companies for update using(public.supplyr_has_company_role(id,array['purchasing','admin']::public.supplyr_member_role[]));
do $$ declare t text; begin foreach t in array array['supplyr_company_members','supplyr_projects','supplyr_suppliers','supplyr_catalog_items','supplyr_supplier_items','supplyr_purchasing_rules','supplyr_material_requests','supplyr_request_items','supplyr_purchase_orders','supplyr_purchase_order_items','supplyr_receipts','supplyr_receipt_items','supplyr_integrations','supplyr_audit_log'] loop execute format('alter table public.%I enable row level security',t); execute format('create policy tenant_read on public.%I for select using (public.supplyr_is_company_member(company_id))',t); end loop; end $$;
create policy members_admin_write on public.supplyr_company_members for all using(public.supplyr_has_company_role(company_id,array['admin']::public.supplyr_member_role[])) with check(public.supplyr_has_company_role(company_id,array['admin']::public.supplyr_member_role[]));
create policy request_create on public.supplyr_material_requests for insert with check(public.supplyr_is_company_member(company_id) and requested_by=auth.uid());
create policy request_owner_update on public.supplyr_material_requests for update using(requested_by=auth.uid() and status in ('draft','rejected')) with check(public.supplyr_is_company_member(company_id));
create policy request_staff_update on public.supplyr_material_requests for update using(public.supplyr_has_company_role(company_id,array['supervisor','purchasing','admin']::public.supplyr_member_role[]));
create policy audit_staff_insert on public.supplyr_audit_log for insert with check(public.supplyr_has_company_role(company_id,array['supervisor','purchasing','admin']::public.supplyr_member_role[]) and actor_id=auth.uid());
create policy request_item_write on public.supplyr_request_items for all using(public.supplyr_is_company_member(company_id) and exists(select 1 from public.supplyr_material_requests r where r.id=request_id and r.company_id=supplyr_request_items.company_id and (r.requested_by=auth.uid() or public.supplyr_has_company_role(r.company_id,array['supervisor','purchasing','admin']::public.supplyr_member_role[])))) with check(public.supplyr_is_company_member(company_id));
do $$ declare t text; begin foreach t in array array['supplyr_projects','supplyr_suppliers','supplyr_catalog_items','supplyr_supplier_items','supplyr_purchasing_rules','supplyr_purchase_orders','supplyr_purchase_order_items','supplyr_receipts','supplyr_receipt_items','supplyr_integrations'] loop execute format('create policy staff_write on public.%I for all using (public.supplyr_has_company_role(company_id,array[''purchasing'',''admin'']::public.supplyr_member_role[])) with check (public.supplyr_has_company_role(company_id,array[''purchasing'',''admin'']::public.supplyr_member_role[]))',t); end loop; end $$;

create or replace function public.supplyr_approve_material_request(p_request_id uuid,p_note text default null) returns jsonb language plpgsql security invoker as $$ declare r public.supplyr_material_requests; begin select * into r from public.supplyr_material_requests where id=p_request_id for update; if r.id is null then raise exception 'Request not found'; end if; if not public.supplyr_has_company_role(r.company_id,array['supervisor','purchasing','admin']::public.supplyr_member_role[]) then raise insufficient_privilege; end if; if r.status <> 'submitted' then raise exception 'Only submitted requests can be approved'; end if; update public.supplyr_material_requests set status='approved',decided_at=now(),decided_by=auth.uid(),updated_at=now() where id=p_request_id returning * into r; insert into public.supplyr_audit_log(company_id,actor_id,entity_type,entity_id,action,after_data) values(r.company_id,auth.uid(),'material_request',r.id,'approved',jsonb_build_object('note',p_note)); return to_jsonb(r); end $$;

-- Atomically allocates PO numbers and splits approved lines by selected supplier.
create or replace function public.supplyr_split_request_into_purchase_orders(p_request_id uuid) returns setof public.supplyr_purchase_orders language plpgsql security invoker as $$
declare r public.supplyr_material_requests; supplier uuid; po public.supplyr_purchase_orders; sequence_no bigint;
begin
  select * into r from public.supplyr_material_requests where id=p_request_id for update;
  if r.status <> 'approved' then raise exception 'Request must be approved'; end if;
  if not public.supplyr_has_company_role(r.company_id,array['purchasing','admin']::public.supplyr_member_role[]) then raise insufficient_privilege; end if;
  if exists(select 1 from public.supplyr_request_items i where i.request_id=r.id and i.selected_supplier_id is null) then raise exception 'Every approved item needs a supplier'; end if;
  for supplier in select distinct selected_supplier_id from public.supplyr_request_items where request_id=r.id loop
    update public.supplyr_companies set next_po_number=next_po_number+1 where id=r.company_id returning next_po_number-1 into sequence_no;
    insert into public.supplyr_purchase_orders(company_id,po_number,supplier_id,project_id,created_by)
      select r.company_id, c.po_prefix||'-'||extract(year from now())::int||'-'||lpad(sequence_no::text,4,'0'),supplier,r.project_id,auth.uid() from public.supplyr_companies c where c.id=r.company_id returning * into po;
    insert into public.supplyr_purchase_order_items(company_id,purchase_order_id,request_item_id,description,quantity,unit,unit_price,supplier_sku)
      select i.company_id,po.id,i.id,i.description,coalesce(i.approved_quantity,i.quantity),i.unit,coalesce(si.unit_price,0),si.supplier_sku from public.supplyr_request_items i left join public.supplyr_supplier_items si on si.company_id=i.company_id and si.catalog_item_id=i.catalog_item_id and si.supplier_id=supplier where i.request_id=r.id and i.selected_supplier_id=supplier;
    update public.supplyr_purchase_orders p set subtotal=(select coalesce(sum(quantity*unit_price),0) from public.supplyr_purchase_order_items where purchase_order_id=p.id) where p.id=po.id returning * into po;
    return next po;
  end loop;
  insert into public.supplyr_audit_log(company_id,actor_id,entity_type,entity_id,action,after_data) values(r.company_id,auth.uid(),'material_request',r.id,'split_into_draft_purchase_orders',jsonb_build_object('request_id',r.id));
end $$;
